apiVersion: v1
kind: Template
metadata:
  name: mongodb-backup-template
  annotations:
    description: 'Template for MongoDB container backup job'
    tags: 'database,backup,mongo'
parameters:
  - name: MONGODB_BACKUP_SCHEDULE
    description: 'Cron-like schedule expression. Default: Once every day at 1:00 AM'
    value: '30 6 * * *'
  - name: MONGODB_BACKUP_VOLUME_CLAIM
    description: 'Name of the volume claim to be used as storage'
    value: ''
objects:
  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: mongodb-backup
    spec:
      schedule: ${MONGODB_BACKUP_SCHEDULE}
      concurrencyPolicy: Forbid
      jobTemplate:
        spec:
          template:
            spec:
              volumes:
                - name: mongodb-backup
                  persistentVolumeClaim:
                    claimName: ${MONGODB_BACKUP_VOLUME_CLAIM}
              containers:
                - name: mongodb-backup
                  image: 'docker-registry.default.svc:5000/openshift/mongodb:latest'
                  command:
                    - 'bash'
                    - '-c'
                    - >-
                      declare -a adminDirFiles=(
                        "system.indexes.bson.gz"
                        "system.users.bson.gz"
                        "system.users.metadata.json.gz"
                        "system.version.bson.gz"
                        "system.version.metadata.json.gz"
                      );

                      declare -a esmDirFiles=(
                        "_defaults.bson.gz"
                        "_defaults.metadata.json.gz"
                        "_permissions.bson.gz"
                        "_permissions.metadata.json.gz"
                        "_roles.bson.gz"
                        "_roles.metadata.json.gz"
                        "activities.bson.gz"
                        "activities.metadata.json.gz"
                        "activitybases.bson.gz"
                        "activitybases.metadata.json.gz"
                        "applications.bson.gz"
                        "applications.metadata.json.gz"
                        "artifacts.bson.gz"
                        "artifacts.metadata.json.gz"
                        "artifacttypes.bson.gz"
                        "artifacttypes.metadata.json.gz"
                        "codelists.bson.gz"
                        "codelists.metadata.json.gz"
                        "collectiondocuments.bson.gz"
                        "collectiondocuments.metadata.json.gz"
                        "collections.bson.gz"
                        "collections.metadata.json.gz"
                        "commentperiods.bson.gz"
                        "commentperiods.metadata.json.gz"
                        "comments.bson.gz"
                        "comments.metadata.json.gz"
                        "communications.bson.gz"
                        "communications.metadata.json.gz"
                        "complaints.bson.gz"
                        "complaints.metadata.json.gz"
                        "conditions.bson.gz"
                        "conditions.metadata.json.gz"
                        "docs.bson.gz"
                        "docs.metadata.json.gz"
                        "documents.bson.gz"
                        "documents.metadata.json.gz"
                        "emailtemplates.bson.gz"
                        "emailtemplates.metadata.json.gz"
                        "enforcements.bson.gz"
                        "enforcements.metadata.json.gz"
                        "folders.bson.gz"
                        "folders.metadata.json.gz"
                        "inspectionreportdetails.bson.gz"
                        "inspectionreportdetails.metadata.json.gz"
                        "inspectionreports.bson.gz"
                        "inspectionreports.metadata.json.gz"
                        "integrations.bson.gz"
                        "integrations.metadata.json.gz"
                        "invitations.bson.gz"
                        "invitations.metadata.json.gz"
                        "irs.bson.gz"
                        "irs.metadata.json.gz"
                        "milestonebases.bson.gz"
                        "milestonebases.metadata.json.gz"
                        "milestones.bson.gz"
                        "milestones.metadata.json.gz"
                        "organizations.bson.gz"
                        "organizations.metadata.json.gz"
                        "phasebases.bson.gz"
                        "phasebases.metadata.json.gz"
                        "phases.bson.gz"
                        "phases.metadata.json.gz"
                        "projectconditions.bson.gz"
                        "projectconditions.metadata.json.gz"
                        "projectgroups.bson.gz"
                        "projectgroups.metadata.json.gz"
                        "projects.bson.gz"
                        "projects.metadata.json.gz"
                        "prototypes.bson.gz"
                        "prototypes.metadata.json.gz"
                        "recentactivities.bson.gz"
                        "recentactivities.metadata.json.gz"
                        "sessions.bson.gz"
                        "sessions.metadata.json.gz"
                        "streams.bson.gz"
                        "streams.metadata.json.gz"
                        "templates.bson.gz"
                        "templates.metadata.json.gz"
                        "topics.bson.gz"
                        "topics.metadata.json.gz"
                        "users.bson.gz"
                        "users.metadata.json.gz"
                        "vcs.bson.gz"
                        "vcs.metadata.json.gz"
                      );

                      ALL_BACKUPS_HEALTHY=true;
                      TAKE_NEW_BACKUP=true;
                      TODAY=$(date +'%d');
                      LAST_YEAR="";
                      LAST_MONTH="";
                      LAST_DAY="";
                      ERROR_MESSAGE="";

                      alertRocketChat () {
                        curl -X POST -H "Content-Type: application/json" --data "{\"username\":\"BakBot\",\"icon_emoji\":\":robot:\",\"text\":\"$1\"}" $ROCKETCHAT_BACKUP_DB_WEBHOOK;
                      }

                      setUnhealthyFolderName () {
                        HEALTHY_STR="$1";
                        echo "Renaming unhealthy backup - $HEALTHY_STR";
                        UNHEALTHY_STR="UNHEALTHY";
                        if [[ $HEALTHY_STR != *"UNHEALTHY"* ]]; then
                          UNHEALTHY_STR=${1/HEALTHY/$UNHEALTHY_STR};
                          echo "Begin move from $UNHEALTHY_STR to $HEALTHY_STR";
                          mv $HEALTHY_STR $UNHEALTHY_STR;
                        fi;
                        ALL_BACKUPS_HEALTHY=false;
                      };

                      deleteBadDump () {
                        echo "Deleting any unhealthy backups";

                        for DUMP_DIR in /var/lib/mongodb-backup/dump-*; do
                          if [[ $DUMP_DIR == *"UNHEALTHY"* ]]; then
                            echo "Unhealthy backup found, deleting $DUMP_DIR and trying again "
                            echo "BEFORE";
                            echo $(ls /var/lib/mongodb-backup);
                            rm -rf $DUMP_DIR;
                            echo "AFTER";
                            echo $(ls /var/lib/mongodb-backup);
                            return;
                          fi;
                        done;
                        echo "No unhealthy backups found, and none deleted";
                      };

                      getLastBackupDate () {
                        echo "Getting last backup date from the file name";
                        LATEST=$(ls -rd /var/lib/mongodb-backup/dump-* | head -1);

                        IFS='-';
                        read -ra DIR <<< "$LATEST";
                        IFS=' ';
                        LAST_TIMESTAMP=${DIR[2]};
                        echo "Last time stamp - $LAST_TIMESTAMP";

                        LAST_YEAR="${LAST_TIMESTAMP:0:4}"
                        LAST_MONTH="${LAST_TIMESTAMP:4:2}"
                        LAST_DAY="${LAST_TIMESTAMP:6:2}"

                        echo "Last successful backup $LAST_DAY, and today is $TODAY" >&2;
                      }

                      checkTakeNewBackup () {
                        echo "Checking whether to take another backup";
                        if [ "$LAST_DAY" = "$TODAY" ]; then
                          echo "Don't take new backup, there was already one taken today.";
                          TAKE_NEW_BACKUP=false;
                        else
                          echo "Last backup was yesterday or before, attempting a new one.";
                        fi;
                      };

                      checkDumps () {
                        echo "Checking for unhealthy backups";

                        for DUMP_DIR in /var/lib/mongodb-backup/dump-*; do

                          for ADMIN_FILE in "${adminDirFiles[@]}"; do
                            if [ ! -f $DUMP_DIR/admin/$ADMIN_FILE ]; then
                              ERROR_MESSAGE="A file is missing in the admin directory.";
                              echo "A file is missing in the admin directory";
                              setUnhealthyFolderName "$DUMP_DIR";
                              return;
                            fi;
                          done;

                          for ESM_FILE in "${esmDirFiles[@]}"; do
                            if [ ! -f $DUMP_DIR/esm/$ESM_FILE ]; then
                              ERROR_MESSAGE="A file is missing in the esm directory.";
                              echo "A file is missing in the esm directory";
                              setUnhealthyFolderName "$DUMP_DIR";
                              return;
                            fi;
                          done;

                          if [ "$(du -sb $DUMP_DIR | cut -f1)" -gt $MONGO_BACKUP_SIZE_UPPER_LIMIT ]; then
                            alertRocketChat "@all BCMI database backup WARNING - Disk usage is approaching capacity. Please transfer backups to larger PVC or decrease the number of backups to keep. Documentation is here https://github.com/bcgov/mem-admin/tree/dev/openshift/templates";
                            return;
                          fi;

                          if [ "$(du -sb $DUMP_DIR | cut -f1)" -lt $MONGO_BACKUP_SIZE_LOWER_LIMIT ]; then
                            ERROR_MESSAGE="The last backup is unusually small.";
                            echo "The last backup is unusually small";
                            setUnhealthyFolderName "$DUMP_DIR";
                            return;
                          fi;

                        done;
                        echo "No new unhealthy backups found.";
                      };

                      deleteBadDump;
                      getLastBackupDate;
                      checkTakeNewBackup;

                      if [ "$TAKE_NEW_BACKUP" = true ]; then
                        echo "Take new backup";
                        DIR=/var/lib/mongodb-backup/dump-`date +%Y%m%d%H%M%S%Z`-HEALTHY;

                        mongodump --numParallelCollections=1 --username=admin --password=$MONGODB_ADMIN_PASSWORD --host=$MONGODB_SERVICE_HOST --port=$MONGODB_SERVICE_PORT --authenticationDatabase=admin --gzip --out=$DIR;

                        checkDumps;

                        if [ "$ALL_BACKUPS_HEALTHY" = true ]; then
                          echo "Trimming old backups";
                          ls -rdt /var/lib/mongodb-backup/dump-* |
                          head -n -$MONGODB_BACKUP_KEEP |
                          xargs rm -rf;

                          alertRocketChat "Backup for BCMI database SUCCESS!";
                          echo;
                          echo "Success";
                          echo "To restore, use:";
                          echo "~# mongorestore -u admin -p \$MONGODB_ADMIN_PASSWORD --authenticationDatabase admin $DIR/DB_TO_RESTORE -d DB_TO_RESTORE_INTO";
                        else
                          echo;
                          TODAY_SEC=$(date +"%s");
                          LAST_BACKUP="$LAST_YEAR-$LAST_MONTH-$LAST_DAY";
                          LAST_BACKUP_SEC=$(date -d "$LAST_BACKUP" +"%s");

                          DIFF_SEC=$(($TODAY_SEC-$LAST_BACKUP_SEC));

                          if [ $DIFF_SEC -gt 172800 ]; then
                            echo "Last successful backup was over two days ago.";
                            alertRocketChat "@all Backups for BCMI database have been FAILING for over two days. The error is - $ERROR_MESSAGE Documentation is here https://github.com/bcgov/mem-admin/tree/dev/openshift/templates";
                          else
                            echo "Last successful backup was within two days ago. Waiting and trying again later.";
                          fi;
                        fi;
                      else
                        echo "Skipping backup as one completed successfully within the last day.";
                      fi;
                  resources:
                  limits:
                    cpu: 500m
                    memory: 2Gi
                  requests:
                    cpu: 100m
                    memory: 512Mi
                  env:
                    - name: MONGODB_ADMIN_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: mongo-secrets
                          key: MONGO_ADMIN_PASSWORD
                    - name: MONGODB_BACKUP_KEEP
                      valueFrom:
                        configMapKeyRef:
                          name: mongo-config
                          key: MONGO_BACKUP_COUNT
                    - name: MONGO_BACKUP_SIZE_LOWER_LIMIT
                      valueFrom:
                        configMapKeyRef:
                          name: mongo-config
                          key: MONGO_BACKUP_SIZE_LOWER_LIMIT
                    - name: MONGO_BACKUP_SIZE_UPPER_LIMIT
                      valueFrom:
                        configMapKeyRef:
                          name: mongo-config
                          key: MONGO_BACKUP_SIZE_UPPER_LIMIT
                    - name: ROCKETCHAT_BACKUP_DB_WEBHOOK
                      valueFrom:
                        configMapKeyRef:
                          name: mongo-config
                          key: ROCKETCHAT_BACKUP_DB_WEBHOOK
                  volumeMounts:
                    - name: mongodb-backup
                      mountPath: /var/lib/mongodb-backup
              restartPolicy: Never
